#!/usr/bash
#gcc -g read_arg.c - -o read_arg
#$gcc -save-temps -g3 read_arg.c - -o read_arg

#gcc read_arg.c -Wl, -e main_try -o read_arg
#gcc -g read_arg.c -Wl, -e main_try -o read_arg
#gcc -g read_arg.c --entry=main_try -o read_arg
#./read_arg arg1 arg2 arg3 arg4 arg5 arg6 --port /dev/usb0 --File /home/data/outputdata.txt

\rm -rf *.i *.s *.o read_arg
