#!/bin/bash
# run like this

export TestUartBuildPath="./build_cmake2"

if [ ! -d ${TestUartBuildPath} ]; then
   mkdir -p ${TestUartBuildPath}
fi

if [ -d ${TestUartBuildPath} ]; then
  cd ${TestUartBuildPath}
  #cmake -G "Unix Makefiles" ..
  cmake ..
  make clean
  make
#  ./Test_uart_Hello
  ./test_uart
  cd -
#  mkdir build_cmake
fi
