#!/bin/bash

# run like this

export Test13BuildPath="./build_cmake"
export Test13SourcePath="."

  #cmake3.13#cmake -B${Test13BuildPath} -S${Test13SourcePath}
  cmake -B${Test13BuildPath} -H${Test13SourcePath}
  cd ${Test13BuildPath}
  make clean
  make
  ./Test13
  cd -
