#!/bin/bash

# run like this

export TestUartBuildPath="./build_cmake"
export TestUartSourcePath="."

  #cmake3._uart#cmake -B${Test_uartBuildPath} -S${Test_uartSourcePath}
  cmake -B${TestUartBuildPath} -H${TestUartSourcePath}
  cd ${TestUartBuildPath}
  make clean
  make
  ./test_uart
  cd -
