#good doc #https://scons.org/doc/production/HTML/scons-user.html#app-functions

#Library('',[])
#Library('TestSharedLib', ['../src_shared/test_shared.c'])
#Library('TestSharedLib', ['../src_shared/test_shared.c'] ,CPPPATH=['../include'])

#Program('',[])
#Program('',[])

#Program('test' ,['../src/test.c' ,CPPPATH=['../src' ,'../scr_shared' ,'../include'] ,['../src/say_hello_.c'] ,LIBS=['TestSharedLib'] ,LIBPATH=['.'])
#Program('test' ,['../src/test.c' ,'../src/say_hello_.c'] ,CPPPATH=['../include'] ,LIBS=['TestSharedLib'] ,LIBPATH=['.'])
#Program('test' ,['../src/test.c' ,'../src/say_hello_.c'] ,CPPPATH=['../include'] ,LIBS=['TestSharedLib'] ,LIBPATH=['.'])

#SConstruct

#env = Environment(CC='gcc' ,CCFLAGS=' -O2 -Wall -g' ,CPPDEFINES=['MyDefine02'])
#
#env = Environment(CC='gcc')
#env = Environment(CXX='g++')
env = Environment(CC='clang')
env = Environment(CXX='clang++')
#
#env.BuildDir('buildpath' ,'src')
#
#env.Append(CCFLAGS=' -Wall -g')
#env.Append(CCFLAGS=' -O2 -Wall -g')
env.Append(CCFLAGS=' -O2 -Wall -g')
env.Append(CFLAGS=' -O2 -Wall -g')
#
#TODO#worked
env.Append(CCFLAGS=' -DPRINT_DEBUG_ENABLE=1')
env.Append(CFLAGS=' -DPRINT_DEBUG_ENABLE=1')
#
env.Replace(CC='clang')
env.Replace(CXX='clang++')
#
env.Prepend(CPPDEFINES=['MyFirstDefine00'])
env.Append(CPPDEFINES=['MyDefine02'])
env.Append(MyVariableAdded01=['MyVariableAdded01'])
print("MyVariableAdded01 = %s" % env['MyVariableAdded01'])
#
opt = env.Clone(CCFLAGS=[' -O2'])
opt = env.Clone(CFLAGS=[' -O2'])
dbg = env.Clone(CCFLAGS=[' -Wall -g'])
dbg = env.Clone(CFLAGS=[' -Wall -g'])
#
#o = opt.Object('test-o' ,['foo.c'])
#opt.Program(o)
##
#d = dbg.Object('test-d' ,['foo.c'])
#dbg.Program(d)

Export ('env')
#Export ("opt", "dbg")
#Export ('opt dbg')
Export ('opt', 'dbg')
#Export ('dbg')

#check the env setting here
print("[env.CC]       is  %s" % env['CC'])
print("[env.CXX]      is  %s" % env['CXX'])
print("[env.CCFLAGS]  is  %s" % env['CCFLAGS'])
print("[env.CFLAGS]   is  %s" % env['CFLAGS'])

objs  = []
header_file_path  = []

#            , variant_dir='build_sc'

#objs.append( SConscript([Glob('./libs/*/SConscript')]           , exports='env')  )

objs.append( SConscript(['./test_main/SConscript']           , exports='env')  )
objs.append( SConscript(['./libs_shared/shared/SConscript']    , exports='env')  )
objs.append( SConscript(['./libs/say_hello/SConscript'] , exports='env')  )
#objs.append( SConscript(['./libs/practice/SConscript']  , exports='env')  )

#print FindFile('SConscript' ,['./libs' ,'./libs_shared'])

#env.Program('test' , objs)
#env.Program('test' ,objs ,CPPPATH=['./include' ,'./libs/shared/header' ,'./libs/say_hello/header' ,'./libs/practice/header'])
env.Program('test_run'
            ,objs
            ,CPPPATH=[
#                        './test_main/header'
#                      , './libs_shared/shared/header'
#                      , './libs/say_hello/header'
                      ])

#            ,'./libs/practice/header'
