#!/bin/bash

# run like this

export TestBuildPath="./build_cmake"
export TestSourcePath="."

  #cmake3.13
  #cmake -B${TestBuildPath} -S${TestSourcePath}
  cmake -B${TestBuildPath} -H${TestSourcePath}
  cd ${TestBuildPath}
  make clean
  make
  ./test_run
  cd -
