#!/bin/bash

export MakeBuildLogFileName="fshan_cbuild_log.txt"

#source try_clean

# run like this
#for gcc make
#make clean
#make all
make all | tee -a ${MakeBuildLogFileName}
#echo "BUILD_DIR is: " $BUILD_DIR
#make
#./build_gcc/test_main
#make run

#for cmake + make case
#cd ./build
#cmake -G "Unix Makefiles" ..
#cmake ..
#make
#./Test_Hello
