#Import('env')
Import('*')

#env.Library('TestSharedLib' ,Glob('*.c[cp]*') ,CPPPATH=['../header'])
#env.StaticLibrary('TestStaticSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['./header'])
#env.SharedLibrary('TestSharedSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['./header'])
#env.SharedLibrary('TestSharedSharedLib' ,Glob('./src/*.c[cp]*') ,CPPPATH=['./header'])
env.SharedLibrary('TestSharedSharedLib'
                  ,Glob('./src/*.c')
                  ,CPPPATH= [
                              './header'
                            #TODO# add item one by one by manual
                            #, './header'
                            ]
                  )

#obj = env.Object([Glob('./src/*.c[cp]*')])
#obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header'])
obj = env.Object([Glob('./src/*.c')] ,CCFLAGS='' ,CPPPATH=['./header'])
Return('obj')
