#Import('env')
Import('*')


#obj = env.Object([Glob('./src/*.c[cp]*')])
#obj = env.Object([Glob('./src/*.c[cp]*')] ,CCFLAGS='' ,CPPPATH=['./header'])
obj = env.Object([Glob('./src/*.c')] ,CCFLAGS='' ,CPPPATH=['./header'])
Return('obj')
