#Library('',[])
#Library('Test11SharedLib', ['../src_shared/test11_shared.c'])
#Library('Test11SharedLib', ['../src_shared/test11_shared.c'] ,CPPPATH=['../include'])

#Program('',[])
#Program('',[])

#Program('test11' ,['../src/test11.c' ,CPPPATH=['../src' ,'../scr_shared' ,'../include'] ,['../src/say_hello_11.c'] ,LIBS=['Test11SharedLib'] ,LIBPATH=['.'])
#Program('test11' ,['../src/test11.c' ,'../src/say_hello_11.c'] ,CPPPATH=['../include'] ,LIBS=['Test11SharedLib'] ,LIBPATH=['.'])
#Program('test11' ,['../src/test11.c' ,'../src/say_hello_11.c'] ,CPPPATH=['../include'] ,LIBS=['Test11SharedLib'] ,LIBPATH=['.'])

#SConstruct

#env = Environment(CC='gcc' ,CCFLAGS=' -O2 -Wall -g' ,CPPDEFINES=['MyDefine01'])
#
env = Environment(CC='gcc')
env.Replace(CC='clang')
#env.Append(CCFLAGS=' -Wall -g')
env.Append(CCFLAGS=' -O2 -Wall -g')
#
env.Prepend(CPPDEFINES=['MyFirstDefine00'])
env.Append(CPPDEFINES=['MyDefine02'])
env.Append(MyVariableAdded01=['MyVariableAdded01'])
print("MyVariableAdded01 = %s" % env['MyVariableAdded01'])
#
opt = env.Clone(CCFLAGS=[' -O2'])
dbg = env.Clone(CCFLAGS=[' -Wall -g'])
#
#env.Program('test11' ,['foo.c'])
#
#o = opt.Object('test11-o' ,['foo.c'])
#opt.Program(o)
##
#d = dbg.Object('test11-d' ,['foo.c'])
#dbg.Program(d)

Export ("env")
Export ("opt")
Export ("dbg")


#SConscript(['src_shared/SConscript']
#            , variant_dir='build_sc_shared'
#            , duplicate=False
#          )
#SConscript(['src/SConscript']
#            , variant_dir='build_sc'
#            , duplicate=False
#          )


SConscript(['src_shared/SConscript']
#            , variant_dir='build_sc_shared'
          )
SConscript(['src/SConscript']
#            , variant_dir='build_sc'
          )
