#Library('',[])
#Library('Test12SharedLib', ['../src_shared/test12_shared.c'])
#Library('Test12SharedLib', ['../src_shared/test12_shared.c'] ,CPPPATH=['../include'])

#Program('',[])

#Program('test12' ,['../src/test12.c' ,CPPPATH=['../src' ,'../scr_shared' ,'../include'] ,['../src/say_hello_12.c'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['.'])
#Program('test12' ,['../src/test12.c' ,'../src/say_hello_12.c'] ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['.'])
#Program('test12' ,['test12.c' ,'say_hello_12.c'] ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../src_shared'])
#Program('test12' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../src_shared'])

#Import('env')
#Import('opt')
#Import('dbg')
#Import ('BuildOutputFilePath')
Import ('*')
#
#env.Program('test12' ,Glob('*.c') ,CPPPATH=['../../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../BuildOutputFilePath/build_sc_shared'])
#env.Program('test12' ,Glob('*.c') ,CPPPATH=['../../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../build_sc_shared'])
#env.Program('test12' ,Glob('*.c') ,CPPPATH=['../../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../' + BuildOutputFilePath + '/build_sc_shared'])
#env.Program('test12' ,Glob('*.c') ,CPPPATH=['../../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../build_sc_shared'])
env.Program('test12' ,Glob('*.c') ,CPPPATH=['../../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../src_shared'])

#env.Program('test12' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../src_shared'])

#opt.Program('test12-opt' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../src_shared'])
#dbg.Program('test12-dbg' ,Glob('*.c') ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['../src_shared'])
