#Library('',[])
#Library('Test12SharedLib', ['../src_shared/test12_shared.c'])
#Library('Test12SharedLib', ['test12_shared.c'] ,CPPPATH=['../include'])
#StaticLibrary('Test12SharedLib' ,Glob('*.c') ,CPPPATH=['../include'])
#Library('Test12SharedLib' ,Glob('*.c') ,CPPPATH=['../include'])

Import('env')
env.Library('Test12SharedLib' ,Glob('*.c') ,CPPPATH=['../include'])

#Program('',[])

#Program('test12' ,['../src/test12.c' ,CPPPATH=['../src' ,'../scr_shared' ,'../include'] ,['../src/say_hello_12.c'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['.'])
#Program('test12' ,['../src/test12.c' ,'../src/say_hello_12.c'] ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['.'])
#Program('test12' ,['../src/test12.c' ,'../src/say_hello_12.c'] ,CPPPATH=['../include'] ,LIBS=['Test12SharedLib'] ,LIBPATH=['.'])
