#!/bin/bash
# run like this

export Test14BuildPath="./build_cmake2"

if [ ! -d ${Test14BuildPath} ]; then
   mkdir -p ${Test14BuildPath}
fi

if [ -d ${Test14BuildPath} ]; then
  cd ${Test14BuildPath}
  #cmake -G "Unix Makefiles" ..
  cmake ..
  make clean
  make
#  ./Test14_Hello
#  ./test14
  ./test14 arg1 arg2 arg3 arg4 arg5 arg6 --port /dev/usb0 --File /home/data/outputdata.txt
  cd -
#  mkdir build_cmake
fi
